name: book-app
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  book_catalog:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3 
      - name: First step
        run:  |
              echo "build image"
              ./script/build-image.sh 
              
      - name: Second step
        run:  |
              echo "kubenetes config"
              ./scripts/kubernetes/deployment.yaml 
