name: book-app
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  book_catalog:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3 
      - name: First step
        run:  |
              echo "CONTAINER_REGISTRY = " $CONTAINER_REGISTRY
              ./index.sh  
              
      - name: Second step
        run:  |
              echo "Hello World!"
              ./index.sh  
